DESCRIPTION="remove \fname{Scsi_Cmnd} typedef"
SP = mega14.cocci

SOURCES = a2091.c \
a3000.c \
acornscsi.c \
aic7xxx_old.c \
aic7xxx_osm.c \
aiclib.c \
fas216.c \
fc.c \
gvp11.c \
ips.c \
microtek.c \
mvme147.c \
nsp_cs.c \
nsp_debug.c \
nsp_message.c \
psi240i.c \
qlogicfas408.c \
queue.c \
seagate.c \
sgiwd93.c \
sun3_NCR5380.c \
sun3_scsi.c \
sun3_scsi_vme.c \
ultrastor.c



TOP=../..
include $(TOP)/generic_makefile
